show_excerpts: true # set to true to show excerpts on the homepage

collections:
  posts:
    permalink: /posts/:title:output_ext
  gallery:
    output: true


#For SEO (jekyll-seo-tag)
description: Персональный сайт Александра Меняйло.
title: Mendeo
author: Александр Меняйло (Mendeo, Themen)
social:
  name: Александр Меняйло
  links:
    - https://github.com/Mendeo
    - https://vk.com/thesolve
    - https://facebook.com/themen1987
    - https://www.instagram.com/mendeo/
      #Наука
    - https://orcid.org/0000-0002-8960-792X
    - https://www.scopus.com/authid/detail.uri?authorId=55490167300
    - https://scholar.google.com/citations?user=4NpFJVQAAAAJ
    - https://www.elibrary.ru/author_items.asp?authorid=735193
image: /assets/portfolio.png
lang: ru-RU
webmaster_verifications:
  yandex: 35a778727acfd8f9
  google: XDYxlXev4ba9l-ewOSofzypY9XsHxlIidHSCUkr8ur8

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
  style: :compressed
plainwhite:
  name: Александр Меняйло
  tagline: Разработчик. Учёный
  date_format: "%d.%m.%Y"
  sitemap: true # set to true to generate sitemap.xml content
  navigation:
    - title: Обо мне
      url: "/about.html"
      modified: 2020-11-03 14:44:00 +03
    - title: Научная деятельность
      url: "/scientist.html"
      modified: 2020-11-03 14:44:00 +03
    - title: Мои проекты
      url: "/projects.html"
      modified: 2020-12-06 13:05:00 +03
    - title: Мои фотографии
      url: "/gallery_test.html"
    - title: Список всех статей
      url: "/contents.html"

  # generate social links in footer
  social_links:
    github:  Mendeo
    vk: thesolve
    instagram: Mendeo
    email: blog@mendeo.ru
    #facebook: themen1987

# Build settings
#theme: plainwhite

feed:
  excerpt_only: true

plugins:
  - jekyll-seo-tag
  #- jekyll-feed
