show_excerpts: true # set to true to show excerpts on the homepage
email: thesolve@mail.ru

#avatar: https://sun9-60.userapi.com/c849428/v849428750/96397/8SZpPmI9z_g.jpg
avatar: /assets/avatar.jpg

#For SEO (jekyll-seo-tag)
description: Персональный сайт Александра Меняйло.
title: Mendeo
author: Александр Меняйло (Mendeo, Themen)
social:
  name: Александр Меняйло
  links:
    - https://github.com/Mendeo
    - https://vk.com/thesolve
    - https://facebook.com/themen1987
    - https://www.instagram.com/mendeo/
      #Наука
    - https://orcid.org/0000-0002-8960-792X
    - https://www.scopus.com/authid/detail.uri?authorId=55490167300
    - https://scholar.google.com/citations?user=4NpFJVQAAAAJ
    - https://www.elibrary.ru/author_items.asp?authorid=735193
image: /assets/portfolio.png
lang: ru-RU
webmaster_verifications:
  yandex: 35a778727acfd8f9
  google: XDYxlXev4ba9l-ewOSofzypY9XsHxlIidHSCUkr8ur8

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Александр Меняйло
  tagline: Разработчик. Учёный
  date_format: "%-d %b, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  navigation:
    - title: Обо мне
      url: "/about.html"
    - title: Научная деятельность
      url: "/scientist.html"
    - title: Мои проекты
      url: "/projects.html"
    - title: Мои фотографии
      url: "/photo.html"

  # generate social links in footer
  social_links:
    github:  Mendeo
    vk: thesolve
    instagram: Mendeo
    #facebook: themen1987

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
#theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
